# Generated by Django 4.0.5 on 2022-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='소개'),
        ),
    ]
